# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  CreateInfra:
    docker:
      - image: amazon/aws-cli
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Create AWS stack using IaS"
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
# Orchestrate jobs using workflows
workflows:
  create-infra-workflow:
    jobs:
      - CreateInfra
